language: java

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3e9a842c5cc5c56a1801
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always

before_install:
 - chmod +x gradlew

addons:
    code_climate:
        repo_token: 9bd8824647c993546257ace05ddc20bb1c2d59bcfce6c0f3862f616cf7389ace

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
